'use client';

import { ReactNode, useEffect } from 'react';
import { cn } from '@/lib/utils';
import { generateExportFilename, type ExportConfig } from '@/lib/renuv-export';

export interface ReviewModeWrapperProps {
  children: ReactNode;
  isActive: boolean;
  exportConfig: ExportConfig;
  className?: string;
}

/**
 * Review/Presentation Mode Wrapper
 * 
 * Strips navigation, applies print-friendly layout, and optimizes for PDF export.
 * When active:
 * - Removes all navigation and controls
 * - Applies clean white background
 * - Optimizes page breaks for print
 * - Adds print-specific metadata
 */
export function ReviewModeWrapper({
  children,
  isActive,
  exportConfig,
  className
}: ReviewModeWrapperProps) {
  
  useEffect(() => {
    if (isActive) {
      // Set document title for PDF export
      const filename = generateExportFilename(exportConfig);
      document.title = filename;
      
      // Add print-specific class to body
      document.body.classList.add('review-mode-active');
      
      // Store metadata for print header/footer
      document.body.dataset.exportBrand = exportConfig.brand;
      document.body.dataset.exportPeriod = exportConfig.periodLabel;
      document.body.dataset.exportDate = new Date().toISOString().split('T')[0];
      
      return () => {
        document.body.classList.remove('review-mode-active');
        delete document.body.dataset.exportBrand;
        delete document.body.dataset.exportPeriod;
        delete document.body.dataset.exportDate;
      };
    }
  }, [isActive, exportConfig]);
  
  return (
    <div 
      className={cn(
        'review-mode-wrapper',
        isActive && 'review-mode-active',
        className
      )}
      data-review-mode={isActive ? 'active' : 'inactive'}
    >
      {isActive && (
        <div className="print-only absolute left-0 right-0 top-0 border-b border-gray-200 bg-white px-8 py-4 text-xs text-gray-600">
          <div className="flex items-center justify-between">
            <div>
              <strong>{exportConfig.brand}</strong> · {exportConfig.periodLabel}
            </div>
            <div>
              Exported: {new Date().toLocaleDateString('en-US', { 
                year: 'numeric', 
                month: 'long', 
                day: 'numeric' 
              })}
            </div>
          </div>
        </div>
      )}
      
      <div 
        className={cn(
          isActive && 'mt-0 bg-white',
          isActive && 'print:mt-16' // Account for print header
        )}
      >
        {children}
      </div>
      
      {isActive && (
        <div className="print-only border-t border-gray-200 bg-white px-8 py-4 text-center text-xs text-gray-500">
          <p>
            Generated by Renuv Amazon Intelligence · {exportConfig.brand} · 
            Confidential & Proprietary
          </p>
        </div>
      )}
    </div>
  );
}

/**
 * Hook for managing review mode state
 */
export function useReviewMode(initialState = false) {
  const [isReviewMode, setIsReviewMode] = useState(initialState);
  
  const toggleReviewMode = () => setIsReviewMode(prev => !prev);
  const enterReviewMode = () => setIsReviewMode(true);
  const exitReviewMode = () => setIsReviewMode(false);
  
  return {
    isReviewMode,
    toggleReviewMode,
    enterReviewMode,
    exitReviewMode,
    setIsReviewMode
  };
}

// Fix missing import
import { useState } from 'react';
